In [1]:
data= input("enter your name ")
print(data)

enter your name  farman ali


farman ali


In [71]:
import numpy as np
oneD=np.array([1,2,3,4,5,6,7,8])
print(oneD)
print(oneD.ndim)
print(oneD.shape)
print(oneD.reshape(4,2))



[1 2 3 4 5 6 7 8]
1
(8,)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
import numpy as np
twoD=np.array([[1,3,4,],[5,6,7]])
print(twoD)
print(twoD.ndim)

[[1 3 4]
 [5 6 7]]
2


In [12]:
import numpy as np
threeD=np.array([[[1,2,3],[5,6,7]]])
print(threeD)
print(threeD.ndim)

[[[1 2 3]
  [5 6 7]]]
3


In [25]:
import numpy as np
oneD=np.array([1,2,3,4,5,6,7,8])
print(oneD)
print(oneD.ndim)
#indexing 
print(oneD[1])
print(oneD[0:8])
print(oneD[-1])
print(oneD[-1:-9])



[1 2 3 4 5 6 7 8]
1
2
[1 2 3 4 5 6 7 8]
8
[]


In [28]:
import numpy as np
twoD=np.array([[1,3,4,],[5,6,7]])
print(twoD)
print(twoD.ndim)
print(twoD[1])
print(twoD[0])
print(twoD[1,2])#7


[[1 3 4]
 [5 6 7]]
2
[5 6 7]
[1 3 4]
7


In [40]:
import numpy as np
threeD=np.array([[[1,2,3],[5,6,7]],[[0,9,3],[9,6,0]],[[0,6,8],[4,3,3]]])
print(threeD)
print(threeD.ndim)
print("index 0",threeD[0])
print("index 1",threeD[1])
print("index 2",threeD[2])
print("index 2,1",threeD[2,1])
print("index 2,1,0",threeD[2,1,0])
print("index 2,1,0:1",threeD[2,1,0:1])




[[[1 2 3]
  [5 6 7]]

 [[0 9 3]
  [9 6 0]]

 [[0 6 8]
  [4 3 3]]]
3
index 0 [[1 2 3]
 [5 6 7]]
index 1 [[0 9 3]
 [9 6 0]]
index 2 [[0 6 8]
 [4 3 3]]
index 2,1 [4 3 3]
index 2,1,0 4
index 2,1,0:1 [4]


In [45]:
import numpy as np
twoD=np.array([[1,3,4,],[5,6,7]])

for i in twoD:
    print(i)

for i in twoD:
    for x in i:
        print(x)


threeD=np.array([[[1,2,3],[5,6,7]],[[0,9,3],[9,6,0]],[[0,6,8],[4,3,3]]])
for i in threeD:
    for x in i:
        for y in x:
            print(y)
            
    

[1 3 4]
[5 6 7]
1
3
4
5
6
7
1
2
3
5
6
7
0
9
3
9
6
0
0
6
8
4
3
3


In [56]:
#zero array
import numpy as np

zeroarray=np.zeros(10)
print(zeroarray)
onesarr=np.ones(10)
print(onesarr)
onesarr=onesarr.astype(int)
print(onesarr)
onesarr=onesarr.astype(float)
print(onesarr)
#prefull with what you want 
onesarr=np.full(100,2)
print(onesarr)






[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [82]:
import numpy as np
#matrix opration
matrix=np.array([[1,2,3,4],[8,6,5,3]])
print(matrix)
print("-----------------------")
print(matrix+2)
print("-----------------------")
print(matrix-4)
print("-----------------------")
print(matrix*4)
print("-----------------------")
print(matrix/3)
print("-----------------------")
print(matrix%4)
print("-----------------------")
print(matrix**2)
#opration are done to every element
print("-----------------------")
print(matrix.T)#transpose
print("-----------------------")
print(matrix+matrix)

print("-----------------------")
print(matrix-matrix)
print("-----------------------")
print(matrix//matrix)
print("-----------------------")
print(matrix%matrix)
matrix=np.array([[1,2,3,4],[8,6,5,3]])
print(matrix)
matrix2=np.array([[3,2,2,4],[8,6,5,9]])
print(matrix2)
print("-----------------------")
print(matrix*matrix2)

print("-----------------------")
#np.matmul(matrix,matrix2)
print("----------min----------",np.min(matrix))

print("----------max----------",np.max(matrix))

print("----------sum----------",np.sum(matrix))
print("----------mean----------",np.mean(matrix))
print("----------STD----------",np.std(matrix))
print("----------median----------",np.median(matrix))








[[1 2 3 4]
 [8 6 5 3]]
-----------------------
[[ 3  4  5  6]
 [10  8  7  5]]
-----------------------
[[-3 -2 -1  0]
 [ 4  2  1 -1]]
-----------------------
[[ 4  8 12 16]
 [32 24 20 12]]
-----------------------
[[0.33333333 0.66666667 1.         1.33333333]
 [2.66666667 2.         1.66666667 1.        ]]
-----------------------
[[1 2 3 0]
 [0 2 1 3]]
-----------------------
[[ 1  4  9 16]
 [64 36 25  9]]
-----------------------
[[1 8]
 [2 6]
 [3 5]
 [4 3]]
-----------------------
[[ 2  4  6  8]
 [16 12 10  6]]
-----------------------
[[0 0 0 0]
 [0 0 0 0]]
-----------------------
[[1 1 1 1]
 [1 1 1 1]]
-----------------------
[[0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [8 6 5 3]]
[[3 2 2 4]
 [8 6 5 9]]
-----------------------
[[ 3  4  6 16]
 [64 36 25 27]]
-----------------------
----------min---------- 1
----------max---------- 8
----------sum---------- 32
----------mean---------- 4.0
----------STD---------- 2.1213203435596424
----------STD---------- 3.5
